# Generated by Django 3.0.7 on 2020-12-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_post_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='사이트')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='제목')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='카테고리')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='지역')),
                ('is_closed', models.CharField(blank=True, max_length=255, null=True, verbose_name='종료여부')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='가격')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
    ]
